//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=4.6.1055.0.
// 
namespace Enza.Services.API.UEL.Proxy
{
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "UELServiceBinding", Namespace = "http://schemas.enzazaden.com/Common/UEL/BPM")]
    public partial class UELServiceBindingService : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private bpm bpmValueField;

        private System.Threading.SendOrPostCallback createUELRecordProcessOperationCompleted;

        /// <remarks/>
        public UELServiceBindingService()
        {
            //this.Url = "Use appropriate end point";
        }

        public bpm bpmValue
        {
            get
            {
                return this.bpmValueField;
            }
            set
            {
                this.bpmValueField = value;
            }
        }

        /// <remarks/>
        public event createUELRecordProcessCompletedEventHandler createUELRecordProcessCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("bpmValue", Direction = System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("createUELRecordProcessResponse", Namespace = "http://schemas.enzazaden.com/Common/UEL/BPM")]
        public createUELRecordProcessResponse createUELRecordProcess([System.Xml.Serialization.XmlElementAttribute("createUELRecordProcess", Namespace = "http://schemas.enzazaden.com/Common/UEL/BPM")] createUELRecordProcess createUELRecordProcess1)
        {
            object[] results = this.Invoke("createUELRecordProcess", new object[] {
                        createUELRecordProcess1});
            return ((createUELRecordProcessResponse)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BegincreateUELRecordProcess(createUELRecordProcess createUELRecordProcess1, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("createUELRecordProcess", new object[] {
                        createUELRecordProcess1}, callback, asyncState);
        }

        /// <remarks/>
        public createUELRecordProcessResponse EndcreateUELRecordProcess(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((createUELRecordProcessResponse)(results[0]));
        }

        /// <remarks/>
        public void createUELRecordProcessAsync(createUELRecordProcess createUELRecordProcess1)
        {
            this.createUELRecordProcessAsync(createUELRecordProcess1, null);
        }

        /// <remarks/>
        public void createUELRecordProcessAsync(createUELRecordProcess createUELRecordProcess1, object userState)
        {
            if ((this.createUELRecordProcessOperationCompleted == null))
            {
                this.createUELRecordProcessOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateUELRecordProcessOperationCompleted);
            }
            this.InvokeAsync("createUELRecordProcess", new object[] {
                        createUELRecordProcess1}, this.createUELRecordProcessOperationCompleted, userState);
        }

        private void OncreateUELRecordProcessOperationCompleted(object arg)
        {
            if ((this.createUELRecordProcessCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createUELRecordProcessCompleted(this, new createUELRecordProcessCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.cordys.com/bpm/instance/1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.cordys.com/bpm/instance/1.0", IsNullable = false)]
    public partial class bpm : System.Web.Services.Protocols.SoapHeader
    {

        private string instance_idField;

        /// <remarks/>
        public string instance_id
        {
            get
            {
                return this.instance_idField;
            }
            set
            {
                this.instance_idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.enzazaden.com/Common/UEL/BPM")]
    public partial class createUELRecordProcess
    {

        private createUelRecord createUelRecordField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://contract.enzazaden.com/uel/logging/v1")]
        public createUelRecord createUelRecord
        {
            get
            {
                return this.createUelRecordField;
            }
            set
            {
                this.createUelRecordField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://contract.enzazaden.com/uel/logging/v1")]
    public partial class createUelRecord
    {

        private string eventTypeField;

        private string subTypeField;

        private string severityField;

        private string environmentField;

        private string locationField;

        private string eventCodeField;

        private string pIDField;

        private string errorDetailTextField;

        private string useridField;

        private string applicationField;

        private createUelRecordInstanceProperties instancePropertiesField;

        /// <remarks/>
        public string EventType
        {
            get
            {
                return this.eventTypeField;
            }
            set
            {
                this.eventTypeField = value;
            }
        }

        /// <remarks/>
        public string SubType
        {
            get
            {
                return this.subTypeField;
            }
            set
            {
                this.subTypeField = value;
            }
        }

        /// <remarks/>
        public string Severity
        {
            get
            {
                return this.severityField;
            }
            set
            {
                this.severityField = value;
            }
        }

        /// <remarks/>
        public string Environment
        {
            get
            {
                return this.environmentField;
            }
            set
            {
                this.environmentField = value;
            }
        }

        /// <remarks/>
        public string Location
        {
            get
            {
                return this.locationField;
            }
            set
            {
                this.locationField = value;
            }
        }

        /// <remarks/>
        public string EventCode
        {
            get
            {
                return this.eventCodeField;
            }
            set
            {
                this.eventCodeField = value;
            }
        }

        /// <remarks/>
        public string PID
        {
            get
            {
                return this.pIDField;
            }
            set
            {
                this.pIDField = value;
            }
        }

        /// <remarks/>
        public string ErrorDetailText
        {
            get
            {
                return this.errorDetailTextField;
            }
            set
            {
                this.errorDetailTextField = value;
            }
        }

        /// <remarks/>
        public string Userid
        {
            get
            {
                return this.useridField;
            }
            set
            {
                this.useridField = value;
            }
        }

        /// <remarks/>
        public string Application
        {
            get
            {
                return this.applicationField;
            }
            set
            {
                this.applicationField = value;
            }
        }

        /// <remarks/>
        public createUelRecordInstanceProperties instanceProperties
        {
            get
            {
                return this.instancePropertiesField;
            }
            set
            {
                this.instancePropertiesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://contract.enzazaden.com/uel/logging/v1")]
    public partial class createUelRecordInstanceProperties
    {

        private string processNameField;

        private string processDescriptionField;

        private string identifierField;

        private string modelSpaceField;

        private string monitorField;

        private string startedByField;

        private string currentOwnerField;

        private string organizationField;

        private string startTimeField;

        private string processInstantiationTypeField;

        private string priorityField;

        private string parentTypeField;

        private string callerInstanceField;

        private string rootInstanceField;

        private string rootInstanceTypeField;

        private createUelRecordInstancePropertiesActivityInfo activityInfoField;

        /// <remarks/>
        public string processName
        {
            get
            {
                return this.processNameField;
            }
            set
            {
                this.processNameField = value;
            }
        }

        /// <remarks/>
        public string processDescription
        {
            get
            {
                return this.processDescriptionField;
            }
            set
            {
                this.processDescriptionField = value;
            }
        }

        /// <remarks/>
        public string identifier
        {
            get
            {
                return this.identifierField;
            }
            set
            {
                this.identifierField = value;
            }
        }

        /// <remarks/>
        public string modelSpace
        {
            get
            {
                return this.modelSpaceField;
            }
            set
            {
                this.modelSpaceField = value;
            }
        }

        /// <remarks/>
        public string monitor
        {
            get
            {
                return this.monitorField;
            }
            set
            {
                this.monitorField = value;
            }
        }

        /// <remarks/>
        public string startedBy
        {
            get
            {
                return this.startedByField;
            }
            set
            {
                this.startedByField = value;
            }
        }

        /// <remarks/>
        public string currentOwner
        {
            get
            {
                return this.currentOwnerField;
            }
            set
            {
                this.currentOwnerField = value;
            }
        }

        /// <remarks/>
        public string organization
        {
            get
            {
                return this.organizationField;
            }
            set
            {
                this.organizationField = value;
            }
        }

        /// <remarks/>
        public string startTime
        {
            get
            {
                return this.startTimeField;
            }
            set
            {
                this.startTimeField = value;
            }
        }

        /// <remarks/>
        public string processInstantiationType
        {
            get
            {
                return this.processInstantiationTypeField;
            }
            set
            {
                this.processInstantiationTypeField = value;
            }
        }

        /// <remarks/>
        public string priority
        {
            get
            {
                return this.priorityField;
            }
            set
            {
                this.priorityField = value;
            }
        }

        /// <remarks/>
        public string parentType
        {
            get
            {
                return this.parentTypeField;
            }
            set
            {
                this.parentTypeField = value;
            }
        }

        /// <remarks/>
        public string callerInstance
        {
            get
            {
                return this.callerInstanceField;
            }
            set
            {
                this.callerInstanceField = value;
            }
        }

        /// <remarks/>
        public string rootInstance
        {
            get
            {
                return this.rootInstanceField;
            }
            set
            {
                this.rootInstanceField = value;
            }
        }

        /// <remarks/>
        public string rootInstanceType
        {
            get
            {
                return this.rootInstanceTypeField;
            }
            set
            {
                this.rootInstanceTypeField = value;
            }
        }

        /// <remarks/>
        public createUelRecordInstancePropertiesActivityInfo activityInfo
        {
            get
            {
                return this.activityInfoField;
            }
            set
            {
                this.activityInfoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://contract.enzazaden.com/uel/logging/v1")]
    public partial class createUelRecordInstancePropertiesActivityInfo
    {

        private createUelRecordInstancePropertiesActivityInfoActivity activityField;

        /// <remarks/>
        public createUelRecordInstancePropertiesActivityInfoActivity activity
        {
            get
            {
                return this.activityField;
            }
            set
            {
                this.activityField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://contract.enzazaden.com/uel/logging/v1")]
    public partial class createUelRecordInstancePropertiesActivityInfoActivity
    {

        private string activityStatusField;

        /// <remarks/>
        public string activityStatus
        {
            get
            {
                return this.activityStatusField;
            }
            set
            {
                this.activityStatusField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.enzazaden.com/Common/UEL/BPM")]
    public partial class createUELRecordProcessResponse
    {

        private createUelRecordResponse createUelRecordResponseField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://contract.enzazaden.com/uel/logging/v1")]
        public createUelRecordResponse createUelRecordResponse
        {
            get
            {
                return this.createUelRecordResponseField;
            }
            set
            {
                this.createUelRecordResponseField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://contract.enzazaden.com/uel/logging/v1")]
    public partial class createUelRecordResponse
    {

        private string resultField;

        private string logIDField;

        /// <remarks/>
        public string result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }

        /// <remarks/>
        public string logID
        {
            get
            {
                return this.logIDField;
            }
            set
            {
                this.logIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void createUELRecordProcessCompletedEventHandler(object sender, createUELRecordProcessCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class createUELRecordProcessCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal createUELRecordProcessCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public createUELRecordProcessResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((createUELRecordProcessResponse)(this.results[0]));
            }
        }
    }
}
