//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enza.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eazy_Vvarieties
    {
        public Nullable<int> EZID { get; set; }
        public string gsysc_syncode { get; set; }
        public int vvarn_varnum { get; set; }
    }
}
