//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enza.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EnzaDbContext : DbContext
    {
        public EnzaDbContext()
            : base("name=EnzaDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Batch> Batches { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<CropGroup> CropGroups { get; set; }
        public virtual DbSet<CropRD> CropRDs { get; set; }
        public virtual DbSet<Entity> Entities { get; set; }
        public virtual DbSet<EntityType> EntityTypes { get; set; }
        public virtual DbSet<FieldSet> FieldSets { get; set; }
        public virtual DbSet<Lot> Lots { get; set; }
        public virtual DbSet<ObsChar> ObsChars { get; set; }
        public virtual DbSet<ObsDate> ObsDates { get; set; }
        public virtual DbSet<ObsDec> ObsDecs { get; set; }
        public virtual DbSet<Observation> Observations { get; set; }
        public virtual DbSet<ObsInt> ObsInts { get; set; }
        public virtual DbSet<PhysicalLocation> PhysicalLocations { get; set; }
        public virtual DbSet<Plant_part_> Plant_part_ { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<PropertyOfEntity> PropertyOfEntities { get; set; }
        public virtual DbSet<Relationship> Relationships { get; set; }
        public virtual DbSet<Trait> Traits { get; set; }
        public virtual DbSet<TraitInFieldSet> TraitInFieldSets { get; set; }
        public virtual DbSet<TraitType> TraitTypes { get; set; }
        public virtual DbSet<TraitValue> TraitValues { get; set; }
        public virtual DbSet<Trial> Trials { get; set; }
        public virtual DbSet<TrialEntry> TrialEntries { get; set; }
        public virtual DbSet<TrialRegion> TrialRegions { get; set; }
        public virtual DbSet<TrialType> TrialTypes { get; set; }
        public virtual DbSet<Variety> Varieties { get; set; }
        public virtual DbSet<VarietyGroup> VarietyGroups { get; set; }
        public virtual DbSet<VarietyInGroup> VarietyInGroups { get; set; }
        public virtual DbSet<Eazy_Bvarieties> Eazy_Bvarieties { get; set; }
        public virtual DbSet<Eazy_FieldBooks> Eazy_FieldBooks { get; set; }
        public virtual DbSet<Eazy_Fields> Eazy_Fields { get; set; }
        public virtual DbSet<Eazy_Lots> Eazy_Lots { get; set; }
        public virtual DbSet<Eazy_Plants> Eazy_Plants { get; set; }
        public virtual DbSet<Eazy_Vvarieties> Eazy_Vvarieties { get; set; }
        public virtual DbSet<ServiceRegistry> ServiceRegistries { get; set; }
    }
}
