//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enza.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lot
    {
        public int EZID { get; set; }
        public string CropCode { get; set; }
        public int LotNr { get; set; }
        public string MasterNr { get; set; }
        public string PONr { get; set; }
        public string GenerationCode { get; set; }
        public string Stem { get; set; }
        public string StemTail { get; set; }
        public string StembookDescription { get; set; }
        public string ResistanceExpected { get; set; }
    
        public virtual CropRD CropRD { get; set; }
        public virtual Entity Entity { get; set; }
    }
}
