//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enza.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObsDec
    {
        public long ObservationID { get; set; }
        public decimal ObsValue { get; set; }
    
        public virtual Observation Observation { get; set; }
    }
}
