//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enza.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyOfEntity
    {
        public int PropertyID { get; set; }
        public string EntityTypeCode { get; set; }
        public int CropGroupID { get; set; }
        public int TraitID { get; set; }
        public Nullable<int> SortingOrder { get; set; }
    
        public virtual CropGroup CropGroup { get; set; }
        public virtual EntityType EntityType { get; set; }
        public virtual Trait Trait { get; set; }
    }
}
