//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enza.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relationship
    {
        public int EZID1 { get; set; }
        public string EntityTypeCode1 { get; set; }
        public int EZID2 { get; set; }
        public string EntityTypeCode2 { get; set; }
    
        public virtual Entity Entity { get; set; }
        public virtual Entity Entity1 { get; set; }
        public virtual EntityType EntityType { get; set; }
        public virtual EntityType EntityType1 { get; set; }
    }
}
