//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enza.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trait
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trait()
        {
            this.Observations = new HashSet<Observation>();
            this.PropertyOfEntities = new HashSet<PropertyOfEntity>();
            this.TraitInFieldSets = new HashSet<TraitInFieldSet>();
            this.TraitValues = new HashSet<TraitValue>();
        }
    
        public int TraitID { get; set; }
        public int CropGroupID { get; set; }
        public string CropCode { get; set; }
        public Nullable<int> ScreeningFieldNr { get; set; }
        public int TraitTypeID { get; set; }
        public string TraitName { get; set; }
        public string ColumnLabel { get; set; }
        public string DataType { get; set; }
        public Nullable<int> ColumnWidth { get; set; }
        public string DisplayFormat { get; set; }
        public bool Editor { get; set; }
        public bool ListOfValues { get; set; }
        public Nullable<int> MinValue { get; set; }
        public Nullable<int> MaxValue { get; set; }
        public bool Property { get; set; }
    
        public virtual CropGroup CropGroup { get; set; }
        public virtual CropRD CropRD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Observation> Observations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyOfEntity> PropertyOfEntities { get; set; }
        public virtual TraitType TraitType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TraitInFieldSet> TraitInFieldSets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TraitValue> TraitValues { get; set; }
    }
}
