//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enza.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trial
    {
        public int EZID { get; set; }
        public string CropCode { get; set; }
        public string TrialName { get; set; }
        public int TrialTypeID { get; set; }
        public string CountryCode { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual CropRD CropRD { get; set; }
        public virtual Entity Entity { get; set; }
        public virtual TrialType TrialType { get; set; }
    }
}
