//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enza.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class VarietyGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VarietyGroup()
        {
            this.VarietyInGroups = new HashSet<VarietyInGroup>();
        }
    
        public int VarietyGroupID { get; set; }
        public string VarietyGroupName { get; set; }
        public int TrialRegionID { get; set; }
        public int Year { get; set; }
    
        public virtual TrialRegion TrialRegion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VarietyInGroup> VarietyInGroups { get; set; }
    }
}
