//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enza.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Variety
    {
        public int EZID { get; set; }
        public Nullable<int> VarietyNr { get; set; }
        public string CropCode { get; set; }
        public string VarietyName { get; set; }
        public string Enumber { get; set; }
        public string CropSegmentCode { get; set; }
        public string ProductSegmentCode { get; set; }
        public string ProductStatus { get; set; }
        public string ResistanceHR { get; set; }
        public string ResistanceIR { get; set; }
        public string ResistanceT { get; set; }
        public string MasterNr { get; set; }
    
        public virtual CropRD CropRD { get; set; }
        public virtual Entity Entity { get; set; }
    }
}
